---
name: Pull Request Tests

'on':
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  hadolint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning
